index:

  name: basic_index

  stages:
    - stage: Preprocessor
      steps:
        - step: OCPreprocessor
          name: simple_pre_processor
          step_args:
            add_punctuation: false
            remove_whitespace: false
          depends_on: [ ]

    - stage: Chunker
      steps:
        - step: OCChunker
          name: simple_chunker
          step_args:
            chunk_size_words: 320
            chunk_overlap: 30
            split_by: word
            split_respect_sentence_boundary: true
            hard_split_max_chars: 2400
          depends_on: [ simple_pre_processor ]

    - stage: Embedder
      steps:
        - step: SentenceTransformerEmbedder
          name: sentence-transformers
          step_args:
            model_name: BAAI/bge-base-en-v1.5
            batch_size: 4
            include_metadata: [ title, file_name ]
          depends_on: [ simple_chunker ]

    - stage: Scorer
      steps:
        - step: LexRank
          name: lexranker_indexing
          step_args:
            update_score_key: lexrank_score_test
            update_percentile_key: lexrank_percentile_test
          depends_on: [ sentence-transformers ]

    - stage: Clusterer
      steps:
        - step: LouvainCommunityDetection
          name: louvain
          step_args:
            update_label_key: louvain_cluster_test
            assign_labels: gpt-3.5-turbo # RateLimit later
          depends_on: [ lexranker_indexing ]


query:

  name: basic_query

  stages:
    - stage: Retriever

      steps:
        - step: OCRetriever
          name: retriever
          step_args:
            query: return me the most important chunks for learning about spectral embeddings
            model_name: BAAI/bge-base-en-v1.5
            top_k: 4
            metadata_filters: { file_name: {"$eq" : "Implicit_representations.pdf"}}
          depends_on: [ ]
