index:

  name: basic_index

  steps:
    - step: OCPreprocessor
      name: simple_pre_processor
      step_args:
        add_punctuation: false
        remove_whitespace: false
      depends_on: [ ]

    - step: OCChunker
      name: simple_chunker
      step_args:
        chunk_size_words: 320
        chunk_overlap: 30
        split_by: word
        split_respect_sentence_boundary: true
        hard_split_max_chars: 2400
      depends_on: [ simple_pre_processor ]

    - step: SentenceTransformerEmbedder
      name: sentence-transformers
      step_args:
        model_name: BAAI/bge-base-en-v1.5
        batch_size: 4
        include_metadata: [ title, file_name ]
      depends_on: [ simple_chunker ]

    - step: LexRank
      name: lexranker_indexing
      step_args:
        update_score_key: lexrank_score_test
        update_percentile_key: lexrank_percentile_test
      depends_on: [ sentence-transformers ]

    - step: LouvainCommunityDetection
      name: louvain
      step_args:
        update_label_key: louvain_cluster_test
        assign_labels: gpt-3.5-turbo # RateLimit later
      depends_on: [ lexranker_indexing ]


query:

  name: basic_query

  steps:
    - step: GetChunks
      name: get_chunks
      step_args:
          metadata_json: { "louvain.louvain_hook"}
          top_k: 400
      depends_on: [ ]
#
#    - step: LexRank
#      name: lexranker_hook
#      step_args:
#      depends_on: [ get_chunks ]
#
#    - step: LouvainCommunityDetection
#      name: louvain_hook
#      step_args:
#      depends_on: [ lexranker_hook ]
#
#    - step: UpdateOnDb
#      name: update_db
#      step_args:
#      depends_on: [ louvain_hook ]
