index:

  name: basic_index

  steps:
    - step: OCPreprocessor
      name: simple_pre_processor
      step_args:
        add_punctuation: false
        remove_whitespace: false
      depends_on: [ ]

    - step: OCChunker
      name: simple_chunker
      step_args:
        chunk_size_words: 320
        chunk_overlap: 30
        split_by: word
        split_respect_sentence_boundary: true
        hard_split_max_chars: 2400
      depends_on: [ simple_pre_processor ]

    - step: SentenceTransformerEmbedder
      name: sentence-transformers
      step_args:
        model_name: BAAI/bge-base-en-v1.5
        batch_size: 4
        include_metadata: [ title, file_name ]
      depends_on: [ simple_chunker ]

    - step: LexRank
      name: lexranker_file
      step_args:
        scope: file
      depends_on: [ sentence-transformers ]

    - step: LouvainCommunityDetection
      name: louvain
      step_args:
        assign_labels: gpt-3.5-turbo # RateLimit later
      depends_on: [ lexranker_file ]


query:

  name: basic_query

  steps:
    - step: OCRetriever
      name: retriever
      step_args:
        query: tell me all about language models please
        model_name: BAAI/bge-base-en-v1.5
        top_k: 50
        metadata_json: { }
      depends_on: [ ]

#    - step: OCReranker
#      name: simple_reranker
#      step_args:
#        query: how much wood could a woodchuck chuck if a woodchuck could chuck wood
#        model_name: BAAI/bge-reranker-base
#        top_k: 10
#        metadata_json: { }
#      depends_on: [ retriever ]
#

